APP_NAME = 'helloworld'
APP_PORT = '3000'

GITHUB_USERNAME = 'miraai'
GITHUB_BASE_URL = 'https://github.com/'
GITHUB_REPO_NAME = '/Ansible'
GITHUB_ANS_REPO =  GITHUB_BASE_URL + GITHUB_USERNAME + GITHUB_REPO_NAME